#!/usr/bin/env bash

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
sudo service nginx restart
sudo service nginx status

